### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by alvaroiporre** [alvaroiporre/JavaScript-Capstone-Project#21]
### Group capstone: set up your Kanban board

We are two people in our team.
- Team member A : @romans-adi .
- Team member B : @alvaroiporre.
Here is the [link](https://github.com/alvaroiporre/JavaScript-Capstone-Project/projects/1).

**Comment by zieeco** [comment]
Hi @Team,

<img height="200" src="https://media1.giphy.com/media/13sz48R33vovLi/giphy.gif"/>


Great job so far! 👏 
You've done well setting up the Kanban board, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice Project setup. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments below._


![image](https://github.com/alvaroiporre/JavaScript-Capstone-Project/assets/59397159/32032acf-bfc1-46f1-8c3f-945f498f28cf)
![image](https://github.com/alvaroiporre/JavaScript-Capstone-Project/assets/59397159/03d0f14d-088c-441e-9e1d-a0ccb20e8eac)
![image](https://github.com/alvaroiporre/JavaScript-Capstone-Project/assets/59397159/02e42bbc-3c90-426e-837a-283bc9e33ead)
![image](https://github.com/alvaroiporre/JavaScript-Capstone-Project/assets/59397159/9d32f08e-0879-4ffc-b245-76b13f2ceb0c)


- :point_up_2:  Hey, the above tasks are group tasks but one team member is assigned to this task. please, kindly update this.

- [ ] Please, kindly tag the names of each team member e.g. Team member A @example. 



## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alvaroiporre** [comment]
Thank you for your feedback @zieeco, we fixed the changes required.

**Comment by danmainah** [comment]
Hi @alvaroiporre and @romans-adi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights

✔️ Kanban board setup correctly with all cards assigned to team members
✔️ Good issue Description with correct info and link

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
